name: Build And Push Nuget Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore
      run: dotnet restore CkTools
    - name: Build
      run: dotnet build CkTools --configuration Release --no-restore -o package
    - name: Push
      run: |
            dotnet nuget push "package/*.nupkg" 
            -k 'oy2bhl42nx3mvdkdgzxqlxydntxmnfuupmdt6l4adbv4cm' 
            -s 'https://api.nuget.org/v3/index.json'  
            --skip-duplicate
    - name: Push Symbol 
      run: |
            dotnet nuget push "package/*.snupkg" 
            -k 'oy2bhl42nx3mvdkdgzxqlxydntxmnfuupmdt6l4adbv4cm' 
            -s 'https://api.nuget.org/v3/index.json'  
            --skip-duplicate
